server:
  port: 5050

spring:
  application:
    name: StoreAPI

  data:
    mongodb:
      uri: mongodb://localhost:27017/store_api
      auto-index-creation: true

jwt:
  secret: "YjNCbGJuTnphQzFyWlhrdGRqRUFBQUFBQkc1dmJtVUFBQUFFYm05dVpRQUFBQUFBQUFBQkFBQUJGd0FBQUFkemMyZ3Rjbk5oQUFBQUF3RUFBUUFBQVFFQTJWRWhtTDQ3WFhoczN0U2Yxd0d2M3lZZjBySzd4SExjVnFST3ZXaWpFMm9WZG1iWTVISDkxbVUyWllDckk4SCtqWGkwejRBZ09lSGV5Tk1YUFA1VjdiZVVvR2QrZm83Q1BRemU2OFhmVERkNjhBbUdMakNyWWJKNElsSlpUS1FNVGZXTXI3Vm1Hbm9lQlh5Qk43NkJRZFJNZkU0T21wckliWFVGMm9xWmdpdjBtQmN4V2VnaFB1dE1HWUc1ZVl3KzVLQ2VmSlg5VWxyWE9MVzF1VHNDc2h2UTFNcXlPeTZ5cWd4Tnl5Znp5VWovT2o0UFpTSExibDF4MzNKbi9QS0hxdDFUQVk3bk9RWk5iNEs1UWhTUVBQMzRCaHBnUVh0RDl6UlJJb3dVQmpUMFpmdlpYalZVR3IrOC9ZRmV2dCszeDZoVk5NNndHeDZYd2NHVWovZ0NXd0FBQThEYThFbDYydkJKZWdBQUFBZHpjMmd0Y25OaEFBQUJBUURaVVNHWXZqdGRlR3plMUovWEFhL2ZKaC9Tc3J2RWN0eFdwRTY5YUtNVGFoVjJadGprY2YzV1pUWmxnS3Nqd2Y2TmVMVFBnQ0E1NGQ3STB4YzgvbFh0dDVTZ1ozNStqc0k5RE43cnhkOU1OM3J3Q1lZdU1LdGhzbmdpVWxsTXBBeE45WXl2dFdZYWVoNEZmSUUzdm9GQjFFeDhUZzZhbXNodGRRWGFpcG1DSy9TWUZ6Rlo2Q0UrNjB3WmdibDVqRDdrb0o1OGxmMVNXdGM0dGJXNU93S3lHOURVeXJJN0xyS3FERTNMSi9QSlNQODZQZzlsSWN0dVhYSGZjbWY4OG9lcTNWTUJqdWM1QmsxdmdybENGSkE4L2ZnR0dtQkJlMFAzTkZFaWpCUUdOUFJsKzlsZU5WUWF2N3o5Z1Y2KzM3ZkhxRlUwenJBYkhwZkJ3WlNQK0FKYkFBQUFBd0VBQVFBQUFRQU45QmVrSnhMSXZhSy83QWNYVnhSano1N2JlSDUxN3FvWEpoV29NNy9FejFyeGIwa2Q0ZlBhZ0VVdDMwVWQxcWJ4am42TmxEeDlldk5ERWNxOEw5aDBtd1VBQjZVbm15TDlxSVhudlp6STJBY2N3bi9MRjNUcG9QdjF1RFBqcCtUaVhKSGI5bG5IK1c5VUN0cUJLY3BDMzg3SmJIbWprNnlxMm9pMXI1Q0x1d2gxZ0R6VjJFWU9oTnBqMWNobXhGVWpON3hXbVVmRU5reXJXWmFTbnF3N3NYN1VteFlLWGlLbnRYd0IwNGVXUTJWbWZSeFUxR09tek1vTHBzYWhPVGFKb1B0T1h4cGxIWllyWTZxa2R2ZWNvMGpYZkdwaGVqc3YwR1lTUGlaM0lETFJqMmhPZ282bkNKWENKclg5WnEzRjhHM0EwVzF4TzVpUXp3WjgvOXNCQUFBQWdBMWFMNFJsM09lRWpFQWk4NWJHMitUbmNyaFRiSGJjUk9LWWlwZ05Va0dHMnd0TE8vZ3Z0MGsyUDJGR0xGbVVrWHhHbVlVUFFoNFdLYkJXZEt6N0RyVVQrZXhEMVBWVkdtWGExbkdPdFhIb2FVSVpFM2NZZE9mdGVmUG0wUEZQNGtFN2VvRHA3alcyOHpMQURrTlhqOEpIdDVRZ0xwYTgwWXFxMWEvajczWW5BQUFBZ1FENEVQWFJaSWhZZ1lhODJRWTd6YTVDVGF6T09yUno1Ris5QXdpZjRseUd0a3ZjMlllY200US9hbGhIMXNiS1gzRGYzODJua1dnUjFuS0gyVHZUbWViMERQekxaY0ZhVGZNdWRQUGQraFRKd09JakdkYzdKMWFTdm9nR2NqTmJpMzN6L3FUbk5ZTElPWmdyZUxySU5VbG0yb293VS9XbExpVXdqVklCNnJsaG93QUFBSUVBNEVScFExdzk5d3lMN1NRK1pZdnh0Qm1UZWJvOUltZEk2Mk1MWXZlbEg5cmEvbEZLT1U2ZTgyRkd4emFaQzUyOUlhd004dWNtT2w5dlBqSDNLNytHdVdmaUxSK014aGRkWXBIT3U2Tm1PQ2JDNjZEOTY4ejNKV3FWaTc2d3hNLzNuUUx5RmswR2JoZ3llSWZwSW5SZ0dhWXJpL3N0MVRwTGkzQlM1cGt0bCtrQUFBQUhiR1ZoWkc5M2N3RUNBd1E9"
  auth-expiration: 28800000
  refresh-expiration: 604800000
  secure: false
  domain: localhost

logging:
  level:
    root: debug
